server:
  port: 8089
  servlet:
    context-path: /springbootmybatis
#整合mybatis相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #mysql5.x驱动版本
    url: jdbc:mysql://120.77.216.183:3306/bootssm?characterEncoding=UTF-8
    username: root
    password: root123
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml #指定mapper配置文件位置
  type-aliases-package: com.example.entity

#配置日志
logging:
  level:
    root: info  #全局日志为debug
    com.example.dao: debug #指定包的日志级别
  file:
    name: run.log #指定生成日志文件名称
    path: ./ #将日志文件生成到当前目录中
